version: '3.2'

services:
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    container_name: appDB
    restart: always
    volumes:
    - "./pkg/database/tableSql:/docker-entrypoint-initdb.d"
    ports:
      - '3306:3306'
    environment:
      MYSQL_DATABASE: todo
      MYSQL_ROOT_PASSWORD: example
  app:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: always
    ports:
      - '8080:80'
    environment:
      PMA_HOST: db
